"""support threads and messages

Revision ID: f71770adff1d
Revises: 55e5e8ce137d
Create Date: 2026-08-13 02:42:38.611514

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as sa_postgresql


# revision identifiers, used by Alembic.
revision = 'f71770adff1d'
down_revision = '55e5e8ce137d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'ACCOUNT', 'CONTRIBUTION', 'SAVINGS', 'WITHDRAWAL', 'OTHER', name='supportcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REPLIED', 'RESOLVED', name='supportstatus'), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('sender_role', sa.String(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['support_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_messages')
    op.drop_table('support_threads')
    # ### end Alembic commands ###